import { IOfferCategory } from 'services/offers/type';

const categoryList:IOfferCategory[] = [
  {
    id: 1,
    displayOrder: 0,
    parentId: null,
    status: 13,
    createdAt: '2022-03-09T08:52:43.000000Z',
    updatedAt: '2022-03-14T02:58:10.000000Z',
    locale: 'vi',
    slug: 'uu-dai-thoi-trang-phu-kien',
    name: 'Ưu đãi thời trang, phụ kiện',
    description: null,
    offerList: [
      {
        id: 1,
        displayOrder: 0,
        isPopular: false,
        thumbnail: '/storage/upload/media/tin-tuc-demo-compress.png',
        publishedAt: '2022-03-14T03:28:00.000000Z',
        visitedCount: 0,
        status: 13,
        showDate: '2022-03-13T17:00:00.000000Z',
        createdAt: '2022-03-14T03:29:11.000000Z',
        updatedAt: '2022-03-15T10:23:49.000000Z',
        locale: 'vi',
        slug: 'nova-fashion-retail-mo-them-cua-hang-thu-60-o-nova-world-ho-tram',
        title: 'Nova Fashion Retail mở thêm cửa hàng thứ 60 ở Nova World Ho Tram',
        description: '',
        content: '',
        tags: [],
        ogTitle: null,
        ogImage: null,
        ogDescription: null,
        categories: [
          {
            id: 1,
            name: 'Ưu đãi thời trang, phụ kiện',
            slug: 'uu-dai-thoi-trang-phu-kien',
          },
        ],
        breadcrumbs: [
          {
            type: 'offer_categories',
            text: 'Ưu đãi thời trang, phụ kiện',
            slug: 'uu-dai-thoi-trang-phu-kien',
          },
        ],
        seoData: {
          title: '',
          description: '',
          keywords: '',
        },
      },
    ],
  },
  {
    id: 1,
    displayOrder: 0,
    parentId: null,
    status: 13,
    createdAt: '2022-03-09T08:52:43.000000Z',
    updatedAt: '2022-03-14T02:58:10.000000Z',
    locale: 'vi',
    slug: 'uu-dai-my-pham',
    name: 'Ưu đãi mỹ phẩm',
    description: null,
    offerList: [
      {
        id: 1,
        displayOrder: 0,
        isPopular: false,
        thumbnail: '/storage/upload/media/tin-tuc-demo-compress.png',
        publishedAt: '2022-03-14T03:28:00.000000Z',
        visitedCount: 0,
        status: 13,
        showDate: '2022-03-13T17:00:00.000000Z',
        createdAt: '2022-03-14T03:29:11.000000Z',
        updatedAt: '2022-03-15T10:23:49.000000Z',
        locale: 'vi',
        slug: 'nova-fashion-retail-mo-them-cua-hang-thu-60-o-nova-world-ho-tram',
        title: 'Nova Fashion Retail mở thêm cửa hàng thứ 60 ở Nova World Ho Tram',
        description: '',
        content: '',
        tags: [],
        ogTitle: null,
        ogImage: null,
        ogDescription: null,
        categories: [
          {
            id: 1,
            slug: 'uu-dai-my-pham',
            name: 'Ưu đãi mỹ phẩm',
          },
        ],
        breadcrumbs: [
          {
            type: 'offer_categories',
            slug: 'uu-dai-my-pham',
            text: 'Ưu đãi mỹ phẩm',
          },
        ],
        seoData: {
          title: '',
          description: '',
          keywords: '',
        },
      },
      {
        id: 2,
        displayOrder: 1,
        isPopular: false,
        thumbnail: '/storage/upload/media/tin-tuc-demo-compress.png',
        publishedAt: '2022-03-14T03:28:00.000000Z',
        visitedCount: 0,
        status: 13,
        showDate: '2022-03-13T17:00:00.000000Z',
        createdAt: '2022-03-14T03:29:11.000000Z',
        updatedAt: '2022-03-15T10:23:49.000000Z',
        locale: 'vi',
        slug: 'nova-fashion-retail-mo-them-cua-hang-thu-60-o-nova-world-ho-tram',
        title: 'Nova Fashion Retail mở thêm cửa hàng thứ 60 ở Nova World Ho Tram',
        description: '',
        content: '',
        tags: [],
        ogTitle: null,
        ogImage: null,
        ogDescription: null,
        categories: [
          {
            id: 1,
            slug: 'uu-dai-my-pham',
            name: 'Ưu đãi mỹ phẩm',
          },
        ],
        breadcrumbs: [
          {
            type: 'offer_categories',
            slug: 'uu-dai-my-pham',
            text: 'Ưu đãi mỹ phẩm',
          },
        ],
        seoData: {
          title: '',
          description: '',
          keywords: '',
        },
      },
    ],
  },
];
export default categoryList;
